name: recommendation-system
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas=2.1.4
  - numpy=1.26.2
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - jupyter
  - ipykernel
  - pip:
      - implicit==0.7.2
      - fastapi==0.108.0
      - uvicorn[standard]==0.25.0
      - pydantic==2.5.3
      - orjson==3.9.10
      - python-multipart==0.0.6
      - pyarrow==14.0.2
      - joblib==1.3.2
      - python-dateutil==2.8.2
      - tqdm==4.66.1
      - locust==2.20.0
      - gradio==4.13.0
      - pytest==7.4.3
      - black==23.12.1
      - flake8==7.0.0
      - click==8.1.7